/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatPreviewRouteImport } from './routes/chat-preview'
import { Route as IndexRouteImport } from './routes/index'

const ChatPreviewRoute = ChatPreviewRouteImport.update({
  id: '/chat-preview',
  path: '/chat-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat-preview': typeof ChatPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat-preview': typeof ChatPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat-preview': typeof ChatPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat-preview'
  id: '__root__' | '/' | '/chat-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatPreviewRoute: typeof ChatPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat-preview': {
      id: '/chat-preview'
      path: '/chat-preview'
      fullPath: '/chat-preview'
      preLoaderRoute: typeof ChatPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatPreviewRoute: ChatPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
